/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class kalkulator1 extends javax.swing.JFrame {
    
    String angka="";
    double jumlah, angka1, angka2;
    int pilih;
    private Object Display;
    /**
     * Creates new form kalkulator1
     */
    public kalkulator1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jPanel1 =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "kalkulator1_jPanel1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();
        display = new javax.swing.JTextField();
        btnAngka6 = new javax.swing.JButton();
        btnAngka7 = new javax.swing.JButton();
        btnAngka8 = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        btnAngka5 = new javax.swing.JButton();
        btnAngka4 = new javax.swing.JButton();
        btnAngka0 = new javax.swing.JButton();
        btnAngka2 = new javax.swing.JButton();
        btnAngka1 = new javax.swing.JButton();
        btnAngka3 = new javax.swing.JButton();
        btnLogbutton = new javax.swing.JButton();
        btnSinbutton = new javax.swing.JButton();
        btnCosbutton = new javax.swing.JButton();
        btnTanbutton = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnAngka9 = new javax.swing.JButton();
        btnSamadengan = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnAkarbutton = new javax.swing.JButton();
        btnBagi1 = new javax.swing.JButton();
        btnPhibutton = new javax.swing.JButton();
        btnPangkatbutton = new javax.swing.JButton();
        btnPersenbutton = new javax.swing.JButton();
        btnPangkatbutton1 = new javax.swing.JButton();
        buttonBSA = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText(" Kalkulator Scientific");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 280, 60));

        display.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 430, 80));

        btnAngka6.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka6.setText("6");
        btnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 60, 40));

        btnAngka7.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka7.setText("7");
        btnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 60, 40));

        btnAngka8.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka8.setText("8");
        btnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 60, 40));

        btnHapus.setBackground(new java.awt.Color(204, 204, 204));
        btnHapus.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnHapus.setText("CE");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, 40));

        btnKoma.setBackground(new java.awt.Color(204, 204, 204));
        btnKoma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKoma.setText(".");
        btnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 60, 40));

        btnAngka5.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka5.setText("5");
        btnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, 40));

        btnAngka4.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka4.setText("4");
        btnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 40));

        btnAngka0.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka0.setText("0");
        btnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka0ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 40));

        btnAngka2.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka2.setText("2");
        btnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 60, 40));

        btnAngka1.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka1.setText("1");
        btnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, 40));

        btnAngka3.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka3.setText("3");
        btnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 60, 40));

        btnLogbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnLogbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLogbutton.setText("log");
        btnLogbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 60, 40));

        btnSinbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnSinbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSinbutton.setText("sin");
        btnSinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnSinbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 40));

        btnCosbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnCosbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCosbutton.setText("cos");
        btnCosbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnCosbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, 40));

        btnTanbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnTanbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnTanbutton.setText("tan");
        btnTanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnTanbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, 40));

        btnTambah.setBackground(new java.awt.Color(204, 204, 204));
        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 50, 40));

        btnAngka9.setBackground(new java.awt.Color(204, 204, 204));
        btnAngka9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAngka9.setText("9");
        btnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAngka9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 60, 40));

        btnSamadengan.setBackground(new java.awt.Color(204, 204, 204));
        btnSamadengan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSamadengan.setText("=");
        btnSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamadenganActionPerformed(evt);
            }
        });
        jPanel1.add(btnSamadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 260, 50));

        btnKali.setBackground(new java.awt.Color(204, 204, 204));
        btnKali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKali.setText("x");
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });
        jPanel1.add(btnKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, 40));

        btnKurang.setBackground(new java.awt.Color(204, 204, 204));
        btnKurang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });
        jPanel1.add(btnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 50, 40));

        btnAkarbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnAkarbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAkarbutton.setText("√");
        btnAkarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkarbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnAkarbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 60, 40));

        btnBagi1.setBackground(new java.awt.Color(204, 204, 204));
        btnBagi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBagi1.setText("÷");
        btnBagi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagi1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBagi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 50, 40));

        btnPhibutton.setBackground(new java.awt.Color(204, 204, 204));
        btnPhibutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPhibutton.setText("phi");
        btnPhibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhibuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnPhibutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 60, 40));

        btnPangkatbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnPangkatbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPangkatbutton.setText("X^Y");
        btnPangkatbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPangkatbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnPangkatbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 60, 40));

        btnPersenbutton.setBackground(new java.awt.Color(204, 204, 204));
        btnPersenbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPersenbutton.setText("%");
        btnPersenbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersenbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(btnPersenbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 60, 40));

        btnPangkatbutton1.setBackground(new java.awt.Color(204, 204, 204));
        btnPangkatbutton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPangkatbutton1.setText("X^2");
        btnPangkatbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPangkatbutton1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPangkatbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 60, 40));

        buttonBSA.setBackground(new java.awt.Color(204, 204, 204));
        buttonBSA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        buttonBSA.setText("C");
        buttonBSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBSAActionPerformed(evt);
            }
        });
        jPanel1.add(buttonBSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("mdls");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 80, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 470);

        setBounds(0, 0, 487, 509);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed
    
    private void btnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka8ActionPerformed
        // TODO add your handling code here:
        angka += "8";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka8ActionPerformed

    private void btnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka6ActionPerformed
        // TODO add your handling code here:
        angka += "6";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka6ActionPerformed

    private void btnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomaActionPerformed
        // TODO add your handling code here:
            angka += ".";
            display.setText(angka);
    }//GEN-LAST:event_btnKomaActionPerformed

    private void btnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka5ActionPerformed
        // TODO add your handling code here:
        angka += "5";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka5ActionPerformed

    private void btnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka4ActionPerformed
        // TODO add your handling code here:
        angka += "4";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka4ActionPerformed

    private void btnAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka0ActionPerformed
        // TODO add your handling code here:
        angka += "0";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka0ActionPerformed

    private void btnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka2ActionPerformed
        // TODO add your handling code here:
        angka += "2";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka2ActionPerformed

    private void btnAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka1ActionPerformed
        // TODO add your handling code here:
        angka += "1";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka1ActionPerformed

    private void btnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka3ActionPerformed
        // TODO add your handling code here:
        angka += "3";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka3ActionPerformed

    private void btnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka9ActionPerformed
        // TODO add your handling code here:
        angka += "9";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka9ActionPerformed

    private void btnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka7ActionPerformed
        // TODO add your handling code here:
        angka += "7";
        display.setText(angka);
    }//GEN-LAST:event_btnAngka7ActionPerformed

    private void btnAkarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkarbuttonActionPerformed
        // TODO add your handling code here:
       angka1=Double.parseDouble(angka);
        display.setText("√");
        angka="";
        pilih=6;
    }//GEN-LAST:event_btnAkarbuttonActionPerformed

    private void btnPangkatbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangkatbuttonActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("^");
        angka="";
        pilih=7;  
    }//GEN-LAST:event_btnPangkatbuttonActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        display.setText("");
        angka1=0.0;
        angka2=0.0;
        jumlah=0.0;
        angka="";
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:     
         angka1=Double.parseDouble(angka);
         display.setText("+");
         angka="";
         pilih=1;
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
         display.setText("-");
         angka="";
         pilih=1;
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnSinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinbuttonActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Sin ");
        angka="";
        pilih=10;
    }//GEN-LAST:event_btnSinbuttonActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnBagi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagi1ActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("/");
        angka="";
        pilih=4;
    }//GEN-LAST:event_btnBagi1ActionPerformed

    private void btnSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamadenganActionPerformed
   // TODO add your handling code here:
       switch(pilih){
   case 1:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 + angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
   case 2:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 - angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
   case 3:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 * angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
   case 4:
            angka2 = Double.parseDouble(angka);
            jumlah = angka1 / angka2;
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
   case 5:
               
            jumlah = Math.pow(angka1, 2);
            angka = Double.toString(jumlah);
            display.setText(angka);
            break;
                
   case 6:
              
           jumlah = Math.sqrt(angka1);
           angka = Double.toString(jumlah);
           display.setText(angka);
           break;
   case 7:
          angka2 = Double.parseDouble(angka);
          jumlah = Math.pow(angka1, angka2);
          angka = Double.toString(jumlah);
          display.setText(angka);  
          break;
   case 8:
             
          jumlah = angka1* 3.14;
          angka = Double.toString(jumlah);
          display.setText(angka);  
          break;
     
               
   case 9:
            
          jumlah = angka1/100;
          angka = Double.toString(jumlah);
          display.setText(angka); 
          break;
   case 10:
            
          jumlah = Math.sin(angka1);
          angka = Double.toString(jumlah);
          display.setText(angka); 
          break;
   case 11:
            
         jumlah = Math.cos(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka); 
         break;
                          
   case 12:    
         jumlah = Math.tan(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka); 
         break;
   case 13:
         angka2 = Double.parseDouble(angka);
         jumlah = Math.log(angka1);
         angka = Double.toString(jumlah);
         display.setText(angka);
         break;
         
   case 14:
       angka2 = Double.parseDouble(angka);
        jumlah = angka1 % angka2;
        angka = Double.toString(jumlah);
        display.setText(angka);

        default:
         break;
       }
    }//GEN-LAST:event_btnSamadenganActionPerformed

    private void btnPhibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhibuttonActionPerformed
        // TODO add your handling code here:
         angka1=Double.parseDouble(angka);
        display.setText("x π ");
        angka="";
        pilih=8;
       
    }//GEN-LAST:event_btnPhibuttonActionPerformed

    private void btnPangkatbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangkatbutton1ActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("^");
        angka="";
        pilih=5;
    }//GEN-LAST:event_btnPangkatbutton1ActionPerformed

    private void btnPersenbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersenbuttonActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText("% ");
        angka="";
        pilih=9;
    }//GEN-LAST:event_btnPersenbuttonActionPerformed

    private void btnCosbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosbuttonActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Cos ");
        angka="";
        pilih=11;
    }//GEN-LAST:event_btnCosbuttonActionPerformed

    private void btnTanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanbuttonActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Tan ");
        angka="";
        pilih=12;

    }//GEN-LAST:event_btnTanbuttonActionPerformed

    private void btnLogbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogbuttonActionPerformed
        // TODO add your handling code here:
        angka1=Double.parseDouble(angka);
        display.setText(" Log ");
        angka="";
        pilih=13; 
    }//GEN-LAST:event_btnLogbuttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        display.setText("mod");
        angka = "";
        pilih = 14;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonBSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBSAActionPerformed
        // TODO add your handling code here:
        display.getText(). length();
        StringBuilder all = new StringBuilder (display.getText());
        char end = all.charAt(all.length() -1);
        all.deleteCharAt(all.length() -1);
        display.setText(all.toString());
        angka = display.getText();
        if (display.getText().length() > 0){
            buttonBSA.setEnabled(true);
        }
    }//GEN-LAST:event_buttonBSAActionPerformed

    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkarbutton;
    private javax.swing.JButton btnAngka0;
    private javax.swing.JButton btnAngka1;
    private javax.swing.JButton btnAngka2;
    private javax.swing.JButton btnAngka3;
    private javax.swing.JButton btnAngka4;
    private javax.swing.JButton btnAngka5;
    private javax.swing.JButton btnAngka6;
    private javax.swing.JButton btnAngka7;
    private javax.swing.JButton btnAngka8;
    private javax.swing.JButton btnAngka9;
    private javax.swing.JButton btnBagi1;
    private javax.swing.JButton btnCosbutton;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnLogbutton;
    private javax.swing.JButton btnPangkatbutton;
    private javax.swing.JButton btnPangkatbutton1;
    private javax.swing.JButton btnPersenbutton;
    private javax.swing.JButton btnPhibutton;
    private javax.swing.JButton btnSamadengan;
    private javax.swing.JButton btnSinbutton;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTanbutton;
    private javax.swing.JButton buttonBSA;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
